### PR TITLE
Add custom migrations path override

### PR DESCRIPTION
**Pull request by RC1140**

### CODE REVIEW

**Comment by wxue** [comment]
👍 
Looking forward for this feature.

**Comment by RC1140** [comment]
Thanks , not entirely sure why the tests are failing

**Comment by taiyangc** [comment]
@RC1140 I believe it's failing because of this search magic: https://github.com/go-pg/migrations/blob/master/collection.go#L132 that excludes the go-pg/migrations/examples/ that have references to `my_table`. But in a new project it doesn't auto-exclude.

Honestly I don't know why it's designed in a way to auto-walk these file paths looking for migrations, instead of specifying a path (which is a normal production flow) in the first place. Maybe the @vmihailenco  can enlighten us the initial considerations. Thanks.

**Comment by vmihailenco** [comment]
Thanks for the PR, but I prefer to export `DiscoverSQLMigrations` instead so existing API is not changed.

**Pull request closed without merging**
